-- Inserciones

use KAILUAHOUSE

INSERT INTO K_ADMINS
VALUES ('kore', 'kore')


INSERT INTO K_CONFIG
VALUES (7, 7, 2)

use KAILUA


INSERT INTO K_ESPECIALIDADES
VALUES ('ASP.NET')
INSERT INTO K_ESPECIALIDADES
VALUES ('Ajax')
INSERT INTO K_ESPECIALIDADES
VALUES ('JScript')
INSERT INTO K_ESPECIALIDADES
VALUES ('Delphi')
INSERT INTO K_ESPECIALIDADES
VALUES ('JAVA')
INSERT INTO K_ESPECIALIDADES
VALUES ('PHP')
INSERT INTO K_ESPECIALIDADES
VALUES ('Ruby')

INSERT INTO K_SECTORES
VALUES ('Medicina')
INSERT INTO K_SECTORES
VALUES ('Biología')
INSERT INTO K_SECTORES
VALUES ('Matemáticas')
INSERT INTO K_SECTORES
VALUES ('Astronomía')
INSERT INTO K_SECTORES
VALUES ('Tecnología')
INSERT INTO K_SECTORES
VALUES ('Telecomunicaciones')
INSERT INTO K_SECTORES
VALUES ('Diseño industrial')
