CREATE DATABASE KAILUA
GO

USE KAILUA 
GO
	

CREATE TABLE K_SECTORES
(
	IdSector	INTEGER IDENTITY (1,1) NOT NULL,
	Denom		VARCHAR(40) NOT NULL,
	
	CONSTRAINT  PK_SECTORES
		PRIMARY KEY (IdSector),
	CONSTRAINT  UQ_DENOM
		UNIQUE (Denom)
)
GO



CREATE TABLE K_CLIENTES
(
	IdCli		INTEGER IDENTITY (1,1) NOT NULL,
	Nombre		VARCHAR(20) NOT NULL,
	Apellidos	VARCHAR(20) NOT NULL,
	NCompleto	AS Nombre + ' ' + Apellidos,
	Empresa		VARCHAR(40) NOT NULL,
	IdSector	INTEGER NOT NULL DEFAULT 0,
	Cargo		VARCHAR(40) NOT NULL,
	EMail		VARCHAR(40) NOT NULL,
	TelContacto CHAR(9) NULL,
	FHAlta		DATETIME NOT NULL DEFAULT Current_TimeStamp,
	Nick        VARCHAR(20) NOT NULL,	
	Clave       VARCHAR(20) NOT NULL,	
	
	CONSTRAINT  PK_CLIENTES
		PRIMARY KEY(IdCli),
	CONSTRAINT  AK_NICKCLI
		UNIQUE (Nick),			
	CONSTRAINT  FK_CL_SECTORES
		FOREIGN KEY (IdSector)		
		REFERENCES K_SECTORES (IdSector)
		ON DELETE SET DEFAULT
		ON UPDATE CASCADE,
	CONSTRAINT  CK_TELCONTACTOCLI
		CHECK (TelContacto LIKE '6%' OR TelContacto LIKE '9%'),
	CONSTRAINT  CK_CLAVECLI
		CHECK (Len(Clave) BETWEEN 4 AND 20),
	CONSTRAINT  CK_NICKCLI
		CHECK (Len(Nick) BETWEEN 4 AND 20)		
)
GO



CREATE TABLE K_CLIENTES_LOGEADOS
(
	Nick		VARCHAR(20) NOT NULL,
	IP			VARCHAR(20) NULL,
	Estado		VARCHAR(12) NOT NULL,
	ZonaActual  VARCHAR(50) NULL,
	FHLogin		DATETIME NULL DEFAULT Current_TimeStamp,
	FHDescon	DATETIME NULL,
	
	CONSTRAINT PK_CLIENTES_LOGEADOS
		PRIMARY KEY (Nick),
	CONSTRAINT FK_CL_CLIENTES
		FOREIGN KEY (Nick)
		REFERENCES K_CLIENTES (Nick)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT CK_ESTADOCLI
		CHECK (Estado IN ('Conectado', 'Desconectado'))		
)
GO



CREATE TABLE K_PROGRAMADORES
(
	IdPro		INTEGER IDENTITY (1,1) NOT NULL,
	Nombre		VARCHAR(20) NOT NULL,
	Apellidos	VARCHAR(40) NOT NULL,
	NCompleto	AS Nombre + ' ' + Apellidos,
	EMail		VARCHAR(40) NOT NULL,
	TelContacto CHAR(9) NULL,
	Empresa		VARCHAR(40) NOT NULL,
	FHAlta		DATETIME NOT NULL DEFAULT Current_TimeStamp,	
	Nick        VARCHAR(20) NOT NULL,	
	Clave       VARCHAR(20) NOT NULL,	

	CONSTRAINT  PK_PROGRAMADORES
		PRIMARY KEY(IdPro),
	CONSTRAINT  AK_NICKPRO
		UNIQUE (Nick),			
	CONSTRAINT  CK_TELCONTACTOPRO
		CHECK (TelContacto LIKE '6%' OR TelContacto LIKE '9%'),
	CONSTRAINT  CK_CLAVEPRO
		CHECK (Len(Clave) BETWEEN 4 AND 20),					
	CONSTRAINT  CK_NICKPRO
		CHECK (Len(Nick) BETWEEN 4 AND 20)		
)
GO


CREATE TABLE K_PROGRAMADORES_LOGEADOS
(
	Nick		VARCHAR(20) NOT NULL,
	IP			VARCHAR(20) NULL,	
	Estado		VARCHAR(12) NOT NULL,	
	ZonaActual  VARCHAR(50) NULL,	
	FHLogin		DATETIME NULL DEFAULT Current_TimeStamp,
	FHDescon	DATETIME NULL,
	
	CONSTRAINT PK_PROGRAMADORES_LOGEADOS
		PRIMARY KEY (Nick),
	CONSTRAINT FK_PL_PROGRAMADORES
		FOREIGN KEY (Nick)
		REFERENCES K_PROGRAMADORES (Nick)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT CK_ESTADOPRO
		CHECK (Estado IN ('Conectado', 'Desconectado'))				
)
GO


CREATE TABLE K_ESPECIALIDADES
(
	IdExp		INTEGER IDENTITY (1,1) NOT NULL,
	Denom		VARCHAR(20) NOT NULL,
	
	CONSTRAINT  PK_ESPECIALIDADES
		PRIMARY KEY (IdExp),
	CONSTRAINT  UQ_DENOMESP
		UNIQUE (Denom)
)
GO


CREATE TABLE K_PROGRAMADORES_ESPECIALIDADES
(
	NickPro		VARCHAR(20) NOT NULL,
	IdEsp		INTEGER NOT NULL,
	
	CONSTRAINT  PK_PROGRAMADORES_ESPECIALIDADES
		PRIMARY KEY (NickPro, IdEsp),
	CONSTRAINT  FK_PE_PROGRAMADORES
		FOREIGN KEY (NickPro)
		REFERENCES K_PROGRAMADORES (Nick)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT  FK_PE_ESPECIALIDADES
		FOREIGN KEY (IdEsp)
		REFERENCES K_ESPECIALIDADES (IdExp)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
)
GO



CREATE TABLE K_NAVEGACION
(
	IdNav   	INTEGER IDENTITY (1,1) NOT NULL,
	Miembro		VARCHAR(20) NULL,
	IP			VARCHAR(20) NOT NULL,
	Pagina		VARCHAR(50) NOT NULL,		
	Navegador	VARCHAR(100) NOT NULL,
	Metodo		VARCHAR(50) NOT NULL,
	FHVisita	DATETIME NOT NULL DEFAULT Current_TimeStamp,
	
	CONSTRAINT  PK_NAVEGACION
		PRIMARY KEY (IdNav)
)
GO


CREATE TABLE K_MENSAJES
(
	IdMensaje	INTEGER IDENTITY (1,1) NOT NULL,
    NickCli		VARCHAR(20) NOT NULL,
	NickPro	    VARCHAR(20) NOT NULL,		
	Direccion   CHAR(6) NOT NULL,      
	Asunto		VARCHAR(40) NOT NULL,
	Texto		VARCHAR(500) NOT NULL,
	DateEnvio	SMALLDATETIME NOT NULL DEFAULT Current_TimeStamp,
	Leido		BIT NOT NULL DEFAULT 0,	
	
	CONSTRAINT  PK_MENSAJES
		PRIMARY KEY (IdMensaje),		
	CONSTRAINT  FK_M_CLIENTE
		FOREIGN KEY (NickCli)
		REFERENCES K_CLIENTES(Nick)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT  FK_M_PROGRAMADOR
		FOREIGN KEY (NickPro)
		REFERENCES K_PROGRAMADORES(Nick)
		ON DELETE CASCADE
		ON UPDATE CASCADE,				
	CONSTRAINT  CK_DIRECCION
		CHECK (Direccion IN ('CliPro', 'ProCli'))
)
GO



CREATE TABLE K_SOFTWARE_OFERTADO
(
	IdSoft			INTEGER IDENTITY (1,1) NOT NULL,
	NickPro			VARCHAR(20) NOT NULL,	
	Tipo			VARCHAR(20) NOT NULL,
	Descrip			VARCHAR(400) NOT NULL,
	Personalizable  BIT NOT NULL DEFAULT 1,
	ConexionBD		BIT NOT NULL DEFAULT 1,
	TipoBD			VARCHAR(30) NULL,
	NickCli			VARCHAR(20) NOT NULL,
	Aceptado		BIT NULL DEFAULT 0,
	FHOferta		SMALLDATETIME NOT NULL DEFAULT Current_TimeStamp,
	
	CONSTRAINT  PK_SOFTWARE_OFERTADO
		PRIMARY KEY (IdSoft),
	CONSTRAINT  FK_S_PROGRAMADOR
		FOREIGN KEY (NickPro)
		REFERENCES K_PROGRAMADORES (Nick)
		ON DELETE CASCADE
		ON UPDATE CASCADE,		
	CONSTRAINT  FK_S_CLIENTE
		FOREIGN KEY (NickCli)
		REFERENCES K_CLIENTES (Nick)
		ON DELETE CASCADE
		ON UPDATE CASCADE,		
	CONSTRAINT CK_TIPO_SO
		CHECK (Tipo IN ('Sitio Web', 'Aplicación Windows')),
	CONSTRAINT CK_TIPOBDOFERTA
		CHECK ((TipoBD IN ('De escritorio', 'Cliente / Servidor')) OR (TipoBD IS NULL))		
)
GO

CREATE TABLE K_SOFTWARE_DEMANDADO
(
	IdSoft		INTEGER IDENTITY (1,1) NOT NULL,
	NickCli     VARCHAR(20) NOT NULL,	
	Tipo		VARCHAR(20) NOT NULL,
	Descrip		VARCHAR(400) NOT NULL,
	ConexionBD	BIT NOT NULL DEFAULT 1,
	TipoBD		VARCHAR(30) NULL,	
	NickPro		VARCHAR(20) NOT NULL,
	Aceptado	BIT NULL DEFAULT 0,
	FHSolicitud SMALLDATETIME NOT NULL DEFAULT Current_TimeStamp,	
	
	CONSTRAINT  PK_SOFTWARE_DEMANDADO
		PRIMARY KEY (IdSoft),
	CONSTRAINT  FK_CLIENTE
		FOREIGN KEY (NickCli)
		REFERENCES K_CLIENTES (Nick)
		ON DELETE CASCADE
		ON UPDATE CASCADE,		
	CONSTRAINT  FK_PROGRAMADOR
		FOREIGN KEY (NickPro)
		REFERENCES K_PROGRAMADORES (Nick)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT CK_TIPO_SD
		CHECK (Tipo IN ('Sitio Web', 'Aplicación Windows')),
	CONSTRAINT CK_TIPOBD
		CHECK ((TipoBD IN ('De escritorio', 'Cliente / Servidor')) OR (TipoBD IS NULL))		
)
GO


CREATE TABLE K_NOTIFICACIONES
(
	IdNotificacion	INTEGER IDENTITY (1,1) NOT NULL,
	Nick			VARCHAR(20) NOT NULL,
	Tipo			VARCHAR(8) NOT NULL,
	Texto			VARCHAR(80) NOT NULL,
	FHNotificacion  SMALLDATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FHCadena		VARCHAR(70) NOT NULL,
	Vista			BIT NOT NULL DEFAULT 0,
	
	CONSTRAINT PK_NOTIFICACIONES
		PRIMARY KEY (IdNotificacion),
		
	CONSTRAINT CK_TIPONOTIFICACION
		CHECK (Tipo IN ('Software', 'Mensaje', 'Ekomomai'))
		
)
GO
