

use KAILUA
-- Inserciones

INSERT INTO K_ESPECIALIDADES
VALUES ('ASP.NET')
INSERT INTO K_ESPECIALIDADES
VALUES ('Ajax')
INSERT INTO K_ESPECIALIDADES
VALUES ('JScript')
INSERT INTO K_ESPECIALIDADES
VALUES ('Delphi')
INSERT INTO K_ESPECIALIDADES
VALUES ('JAVA')
INSERT INTO K_ESPECIALIDADES
VALUES ('PHP')
INSERT INTO K_ESPECIALIDADES
VALUES ('Ruby')

INSERT INTO K_SECTORES
VALUES ('Medicina')
INSERT INTO K_SECTORES
VALUES ('Biología')
INSERT INTO K_SECTORES
VALUES ('Matemáticas')
INSERT INTO K_SECTORES
VALUES ('Astronomía')
INSERT INTO K_SECTORES
VALUES ('Tecnología')
INSERT INTO K_SECTORES
VALUES ('Telecomunicaciones')
INSERT INTO K_SECTORES
VALUES ('Diseño industrial')

EXECUTE ENVIAR_MENSAJE 'kepler', 'albert', 'CliPro', 'también yo', 'que programas bien'

EXECUTE VER_MENSAJES_PARA 'CliPro', '', 'albert', 1

EXECUTE VER_MENSAJES_PARA 'ProCli', 'kepler', '', 1















