CREATE DATABASE KAILUAHOUSE
GO

USE KAILUAHOUSE
GO

CREATE TABLE K_ADMINS
(
	IdAdmin    INTEGER IDENTITY (1,1) NOT NULL,
	Usuario		 VARCHAR(20) NOT NULL,
	ClaveAcceso	 VARCHAR(20) NOT NULL,
	
	CONSTRAINT PK_ADMINS
		PRIMARY KEY (IdAdmin),
	CONSTRAINT UQ_USUARIO
		UNIQUE (Usuario)
)
GO


CREATE TABLE K_CONFIG
(
	LecturaNav		SMALLINT NOT NULL,
	LecturaLogs		SMALLINT NOT NULL,
	Reconstruccion  SMALLINT NOT NULL,
	
	CONSTRAINT	PK_CONFIG
		PRIMARY KEY(LecturaNav, LecturaLogs, Reconstruccion),
	CONSTRAINT CK_LECTURANAV
		CHECK (LecturaNav BETWEEN 3 AND 3600),
	CONSTRAINT CK_LECTURALOGS
		CHECK (LecturaLogs BETWEEN 2 AND 3600),
	CONSTRAINT CK_RECONSTRUCCION
		CHECK (Reconstruccion BETWEEN 1 AND 48)		
)
GO


CREATE TABLE KH_ZONAS
(
	IdEntrada    INTEGER IDENTITY (1,1) NOT NULL,
	Zona		 VARCHAR(40) NOT NULL,
	NumVisitas   INTEGER NOT NULL,
	FHLastUpdate DATETIME NOT NULL DEFAULT Current_TimeStamp,
	
	CONSTRAINT PK_ZONAS
		PRIMARY KEY (IdEntrada),
	CONSTRAINT UQ_ZONA
		UNIQUE (Zona),
	CONSTRAINT CK_NUMVISITAS_ZONAS
		CHECK (NumVisitas >= 0)
)
GO

CREATE TABLE KH_USUARIOS
(
	IdEntrada		INTEGER IDENTITY (1,1) NOT NULL,
	Usuario			VARCHAR(20) NOT NULL,
	Tipo			VARCHAR(11) NOT NULL,
	Zona			VARCHAR(40) NOT NULL,
	NumVisitas		INTEGER NOT NULL,
	FHLastUpdate    DATETIME NOT NULL DEFAULT Current_TimeStamp,
	
	CONSTRAINT PK_USUARIOS
		PRIMARY KEY (IdEntrada),
	CONSTRAINT UQ_USUARIO_ZONA
		UNIQUE (Usuario, Zona),
	
	CONSTRAINT CK_TIPO
		CHECK (Tipo IN ('Cliente', 'Programador', 'Visitante')),
	CONSTRAINT CK_NUMVISITAS_USUARIO
		CHECK (NumVisitas >= 0)
)
GO
	
CREATE TABLE KH_NAVEGADORES
(
	IdEntrada		INTEGER IDENTITY (1,1) NOT NULL,
	Navegador		VARCHAR(30) NOT NULL,
	NumUsers		INTEGER NOT NULL,
	FHLastUpdate	DATETIME NOT NULL DEFAULT Current_TimeStamp,
	
	CONSTRAINT PK_NAVEGADORES
		PRIMARY KEY (IdEntrada),
	CONSTRAINT UQ_NAVEGADOR
		UNIQUE (Navegador),
	CONSTRAINT CK_NUMUSERS
		CHECK (NumUsers > 0)
)
GO


CREATE TABLE KH_SOLICITUDES_SOFTWARE
(
	IdEntrada			INTEGER IDENTITY (1,1) NOT NULL,
	Cliente				VARCHAR(20) NOT NULL,
	SolsWindows 		INTEGER NOT NULL,
	SolsWinConBDLocal	INTEGER NOT NULL,
	SolsWinConBDCS		INTEGER NOT NULL,
	SolsWeb				INTEGER NOT NULL,
	SolsWebConBD		INTEGER NOT NULL,
	FHLastUpdate		SMALLDATETIME NOT NULL DEFAULT Current_TimeStamp,
	
	CONSTRAINT PK_SOLICITUDES_SOFTWARE
		PRIMARY KEY (IdEntrada),
	CONSTRAINT UQ_CLIENTE
		UNIQUE (Cliente)	
)
GO


CREATE TABLE KH_OFERTAS_SOFTWARE
(
	IdEntrada				INTEGER IDENTITY (1, 1) NOT NULL,
	Programador				VARCHAR(20) NOT NULL,
	OfertasWindows			INTEGER NOT NULL,
	OfertasWinConBDLocal	INTEGER NOT NULL,
	OfertasWinConBDCS		INTEGER NOT NULL,
	OfertasWeb				INTEGER NOT NULL,
	OfertasWebConBD			INTEGER NOT NULL,
	FHLastUpdate			SMALLDATETIME NOT NULL DEFAULT Current_TimeStamp,
	
	CONSTRAINT PK_OFERTAS_SOFTWARE
		PRIMARY KEY (IdEntrada),
	CONSTRAINT UQ_PROGRAMADOR
		UNIQUE (Programador)
)
GO



CREATE TABLE KH_SECTORES
(
	IdEntrada		INTEGER IDENTITY (1, 1) NOT NULL,
	Sector			VARCHAR(40) NOT NULL,
	NumClientes		INTEGER NOT NULL,
	FHLastUpdate SMALLDATETIME NOT NULL DEFAULT Current_TimeStamp,	
	
	CONSTRAINT PK_SECTORES
		PRIMARY KEY (IdEntrada)
)
GO


CREATE TABLE KH_ESPECIALIDADES
(
	IdEntrada		INTEGER IDENTITY (1, 1) NOT NULL,
	Especialidad	VARCHAR(20) NOT NULL,
	NumProgrammers	INTEGER NOT NULL,
	FHLastUpdate SMALLDATETIME NOT NULL DEFAULT Current_TimeStamp,	
	
	CONSTRAINT PK_ESPECIALIDADES
		PRIMARY KEY (IdEntrada)
)
GO


CREATE TABLE K_NAVEGACION_DUPLICADO
(
	IdNav   	INTEGER IDENTITY (1,1) NOT NULL,
	Miembro		VARCHAR(20) NULL,
	IP			VARCHAR(20) NOT NULL,
	Pagina		VARCHAR(50) NOT NULL,		
	Navegador	VARCHAR(100) NOT NULL,
	Metodo		VARCHAR(50) NOT NULL,
	FHVisita	DATETIME NOT NULL DEFAULT Current_TimeStamp,
	
	CONSTRAINT  PK_NAVEGACION
		PRIMARY KEY (IdNav)
)
GO

