USE KAILUAHOUSE
GO

INSERT INTO K_CONFIG
VALUES (8, 8, 3)

INSERT INTO KH_ADMINS
VALUES ('kore', 'kore')


DELETE FROM KH_ZONAS
DELETE FROM KH_USUARIOS
DELETE FROM KH_ESPECIALIDADES
DELETE FROM KH_NAVEGADORES
DELETE FROM KH_SECTORES
DELETE FROM K_NAVEGACION_DUPLICADO


EXECUTE BUILD_HOUSE


SELECT * FROM KH_ZONAS
SELECT * FROM KH_USUARIOS
SELECT * FROM KH_ESPECIALIDADES
SELECT * FROM KH_SECTORES
SELECT * FROM KH_NAVEGADORES
SELECT * FROM KH_SOLICITUDES_SOFTWARE
SELECT * FROM KH_OFERTAS_SOFTWARE



select SUM(numvisitas) from KH_USUARIOS
where Zona = 'Inicio'

